using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Moyai.Application.Builds;
using Moyai.Application.Lifecycle;
using Moyai.Application.Projects;
using Moyai.Application.Releases;
using Moyai.Domain.Builds;
using Moyai.Domain.Deployments;
using Moyai.Domain.Events;
using Moyai.Domain.Projects;
using Moyai.Domain.Releases;

namespace Moyai.Application.Deployments;

/// <summary>Local／Server Deploymentを統括し、状態と履歴を管理します。</summary>
public sealed class DeploymentService(IProjectRepository projects, IBuildRepository builds, IReleaseRepository releases, IDeploymentRepository deployments, LifecycleService lifecycle, TimeProvider timeProvider)
{
    public async Task<DeploymentTarget> GetTargetAsync(string projectName, CancellationToken token = default) { Project project = await ProjectAsync(projectName, token); return await deployments.GetTargetAsync(project.Id, token) ?? throw new KeyNotFoundException("Deployment target was not found."); }
    public async Task<DeploymentTarget> UpdateTargetAsync(string projectName, string name, string mode, string destinationPath, string? kelpieTarget, string? configJson, long expectedRevision, string actorType, string actorName, CancellationToken token = default)
    {
        Project project = await ProjectAsync(projectName, token); if (!string.Equals(project.DeployMode, mode, StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("Deployment target mode must match the Project deploy mode.");
        DeploymentTarget target = DeploymentTarget.Create(project.Id, name, mode, destinationPath, kelpieTarget, configJson, timeProvider); await deployments.UpsertTargetAsync(target, expectedRevision, Event(project.Id, target.Id, "deployment_target_updated", actorType, actorName, target), token); return await deployments.GetTargetAsync(project.Id, token) ?? target;
    }
    public async Task<Deployment> StartAsync(string projectName, Guid buildId, Guid artifactId, string? releaseVersion, string actorType, string actorName, CancellationToken token = default)
    {
        Project project = await ProjectAsync(projectName, token); DeploymentTarget target = await EnsureTarget(project, actorType, actorName, token); Build build = await builds.GetAsync(project.Id, buildId, token) ?? throw new KeyNotFoundException("Build was not found."); if (build.Status != BuildStatus.Succeeded) throw new InvalidOperationException("Only a succeeded Build can be deployed."); BuildArtifact artifact = (await builds.ListArtifactsAsync(project.Id, buildId, token)).SingleOrDefault(value => value.Id == artifactId) ?? throw new KeyNotFoundException("Build artifact was not found.");
        Release? release = releaseVersion is null ? null : await releases.GetAsync(project.Id, releaseVersion, cancellationToken: token) ?? throw new ReleaseNotFoundException(releaseVersion); Deployment? previous = (await deployments.ListAsync(project.Id, token)).FirstOrDefault(static value => value.Status == DeploymentStatus.Succeeded);
        Deployment deployment = Deployment.Create(project.Id, target, build.Id, release?.Id, build.SourceCommit, previous?.Id, null, actorType, actorName, timeProvider); await deployments.AddAsync(deployment, Event(project.Id, deployment.Id, "deployment_started", actorType, actorName, deployment), token); return await Execute(projectName, deployment, project.SourcePath, artifact, releaseVersion, token);
    }
    public async Task<Deployment> RetryAsync(string projectName, Guid deploymentId, Guid artifactId, string actorType, string actorName, CancellationToken token = default) { Deployment failed = await GetAsync(projectName, deploymentId, token); if (failed.Status != DeploymentStatus.Failed) throw new InvalidOperationException("Only a failed Deployment can be retried."); Project project = await ProjectAsync(projectName, token); BuildArtifact artifact = (await builds.ListArtifactsAsync(project.Id, failed.BuildId, token)).SingleOrDefault(value => value.Id == artifactId) ?? throw new KeyNotFoundException("Build artifact was not found."); DeploymentTarget target = await GetTargetAsync(projectName, token); Deployment retry = Deployment.Create(project.Id, target, failed.BuildId, failed.ReleaseId, failed.SourceCommit, failed.PreviousDeploymentId, null, actorType, actorName, timeProvider); await deployments.AddAsync(retry, Event(project.Id, retry.Id, "deployment_started", actorType, actorName, retry), token); return await Execute(projectName, retry, project.SourcePath, artifact, null, token); }
    public async Task<Deployment> RollbackAsync(string projectName, Guid deploymentId, string actorType, string actorName, CancellationToken token = default)
    {
        Project project = await ProjectAsync(projectName, token); Deployment original = await GetAsync(projectName, deploymentId, token); if (original.Status != DeploymentStatus.Succeeded) throw new InvalidOperationException("Only a succeeded Deployment can be rolled back."); DeploymentTarget target = await GetTargetAsync(projectName, token); Deployment rollback = Deployment.Create(project.Id, target, original.BuildId, original.ReleaseId, original.SourceCommit, original.PreviousDeploymentId, original.Id, actorType, actorName, timeProvider); await deployments.AddAsync(rollback, Event(project.Id, rollback.Id, "deployment_rollback_started", actorType, actorName, rollback), token); await Transition(rollback, DeploymentStatus.RollingBack, "deployment_rollback_started", token);
        try { if (rollback.Mode == "local") RollbackLocal(original); else { LifecycleResult result = await lifecycle.ExecuteAsync(projectName, LifecycleAction.DeployRollback, actorType, actorName, artifactPath: original.DestinationPath, cancellationToken: token); if (!result.Ok) throw new InvalidOperationException(result.ErrorMessage ?? "Server rollback failed."); } await Transition(rollback, DeploymentStatus.RolledBack, "deployment_rolled_back", token); }
        catch (Exception exception) { await Transition(rollback, DeploymentStatus.RollbackFailed, "deployment_rollback_failed", CancellationToken.None, "rollback_failed", exception.Message); }
        return rollback;
    }
    public async Task<Deployment> GetAsync(string projectName, Guid id, CancellationToken token = default) { Project project = await ProjectAsync(projectName, token); return await deployments.GetAsync(project.Id, id, token) ?? throw new KeyNotFoundException("Deployment was not found."); }
    public async Task<IReadOnlyList<Deployment>> ListAsync(string projectName, CancellationToken token = default) => await deployments.ListAsync((await ProjectAsync(projectName, token)).Id, token);
    private async Task<Deployment> Execute(string projectName, Deployment deployment, string sourcePath, BuildArtifact artifact, string? releaseVersion, CancellationToken token)
    {
        try { await Transition(deployment, DeploymentStatus.Preparing, "deployment_preparing", token); string artifactPath = Path.GetFullPath(artifact.FilePath, sourcePath); await VerifyArtifact(artifact, artifactPath, token); await Transition(deployment, DeploymentStatus.Deploying, "deployment_deploying", token); if (deployment.Mode == "local") DeployLocal(deployment, artifactPath); else { LifecycleResult result = await lifecycle.ExecuteAsync(projectName, LifecycleAction.Deploy, deployment.ActorType, deployment.ActorName, releaseVersion, artifactPath, cancellationToken: token); if (!result.Ok) throw new InvalidOperationException(result.ErrorMessage ?? "Server deploy failed."); } await Transition(deployment, DeploymentStatus.Verifying, "deployment_verifying", token); VerifyLocalDestination(deployment, artifact); await Transition(deployment, DeploymentStatus.Succeeded, "deployment_succeeded", token); }
        catch (Exception exception) { await Transition(deployment, DeploymentStatus.Failed, "deployment_failed", CancellationToken.None, "deployment_failed", exception.Message); }
        return deployment;
    }
    private async Task Transition(Deployment d, DeploymentStatus status, string eventType, CancellationToken token, string? code = null, string? message = null) { long revision = d.Revision; d.Transition(status, timeProvider, code, message); await deployments.UpdateAsync(d, revision, Event(d.ProjectId, d.Id, eventType, d.ActorType, d.ActorName, d), token); }
    private async Task<DeploymentTarget> EnsureTarget(Project p, string actorType, string actorName, CancellationToken token) { DeploymentTarget? target = await deployments.GetTargetAsync(p.Id, token); if (target is not null) return target; if (p.DeployMode != "local" || p.InstallPath is null) throw new KeyNotFoundException("Deployment target was not found."); return await UpdateTargetAsync(p.Name, "default", "local", p.InstallPath, null, null, 0, actorType, actorName, token); }
    private static void DeployLocal(Deployment d, string artifactPath) { string staging = $"{d.DestinationPath}.moyai-staging-{d.Id:N}"; string backup = Backup(d); if (Directory.Exists(staging)) Directory.Delete(staging, true); Directory.CreateDirectory(staging); if (File.Exists(artifactPath)) File.Copy(artifactPath, Path.Combine(staging, Path.GetFileName(artifactPath)), true); else CopyDirectory(artifactPath, staging); if (Directory.Exists(backup)) Directory.Delete(backup, true); if (Directory.Exists(d.DestinationPath)) Directory.Move(d.DestinationPath, backup); Directory.Move(staging, d.DestinationPath); }
    private static void RollbackLocal(Deployment d) { string backup = Backup(d); if (!Directory.Exists(backup)) throw new DirectoryNotFoundException("Rollback backup was not found."); string failed = $"{d.DestinationPath}.moyai-failed-{d.Id:N}"; if (Directory.Exists(failed)) Directory.Delete(failed, true); if (Directory.Exists(d.DestinationPath)) Directory.Move(d.DestinationPath, failed); Directory.Move(backup, d.DestinationPath); }
    private static string Backup(Deployment d) => $"{d.DestinationPath}.moyai-backup-{d.Id:N}";
    private static void CopyDirectory(string source, string destination) { foreach (string directory in Directory.EnumerateDirectories(source, "*", SearchOption.AllDirectories)) Directory.CreateDirectory(Path.Combine(destination, Path.GetRelativePath(source, directory))); foreach (string file in Directory.EnumerateFiles(source, "*", SearchOption.AllDirectories)) { string target = Path.Combine(destination, Path.GetRelativePath(source, file)); Directory.CreateDirectory(Path.GetDirectoryName(target)!); File.Copy(file, target, true); } }
    private static void VerifyLocalDestination(Deployment d, BuildArtifact a) { if (d.Mode != "local") return; if (!Directory.Exists(d.DestinationPath)) throw new InvalidOperationException("Deployment verification failed."); if (a.ArtifactKind == "file" && !File.Exists(Path.Combine(d.DestinationPath, Path.GetFileName(a.FilePath)))) throw new InvalidOperationException("Deployment verification failed."); }
    private static async Task VerifyArtifact(BuildArtifact a, string path, CancellationToken token) { if (a.ArtifactKind == "file") { await using FileStream stream = File.OpenRead(path); string hash = Convert.ToHexString(await SHA256.HashDataAsync(stream, token)).ToLowerInvariant(); if (!string.Equals(hash, a.Sha256, StringComparison.Ordinal)) throw new InvalidOperationException("Artifact hash mismatch."); } else { var manifest = new StringBuilder(); foreach (string file in Directory.EnumerateFiles(path, "*", SearchOption.AllDirectories).Order(StringComparer.Ordinal)) { await using FileStream stream = File.OpenRead(file); manifest.Append(Path.GetRelativePath(path, file).Replace('\\', '/')).Append('\t').Append(Convert.ToHexString(await SHA256.HashDataAsync(stream, token)).ToLowerInvariant()).Append('\n'); } string hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(manifest.ToString()))).ToLowerInvariant(); if (!string.Equals(hash, a.ManifestSha256, StringComparison.Ordinal)) throw new InvalidOperationException("Artifact manifest hash mismatch."); } }
    private async Task<Project> ProjectAsync(string name, CancellationToken token) => await projects.GetRequiredAsync(name, token).ConfigureAwait(false);
    private ProjectEvent Event(Guid projectId, Guid entityId, string type, string actorType, string actorName, object value) => ProjectEvent.Create(projectId, "deployment", entityId, type, actorType, actorName, null, JsonSerializer.Serialize(value), null, timeProvider);
}
