using System.Globalization;
using Microsoft.Data.Sqlite;
using Moyai.Application.Deployments;
using Moyai.Application.Projects;
using Moyai.Domain.Deployments;
using Moyai.Domain.Events;

namespace Moyai.Infrastructure.Persistence;

/// <summary>Deployment Target、Deployment、EventをSQLiteへ永続化します。</summary>
public sealed class SqliteDeploymentRepository(SqliteDatabaseOptions options) : IDeploymentRepository
{
    private const string DeploymentSelect = "SELECT id,project_id,deployment_target_id,build_id,release_id,mode,status,source_commit,destination_path,kelpie_target,previous_deployment_id,rollback_of_deployment_id,started_at,finished_at,actor_type,actor_name,error_code,error_message,created_at,revision FROM deployments";
    public async Task<DeploymentTarget?> GetTargetAsync(Guid projectId, CancellationToken cancellationToken = default) { await using SqliteConnection c = await Open(cancellationToken); await using SqliteCommand q = c.CreateCommand(); q.CommandText = "SELECT id,project_id,name,mode,destination_path,kelpie_target,config_json,created_at,updated_at,revision FROM deployment_targets WHERE project_id=$project;"; q.Parameters.AddWithValue("$project", F(projectId)); await using SqliteDataReader r = await q.ExecuteReaderAsync(cancellationToken); return await r.ReadAsync(cancellationToken) ? new(ParseGuid(r, 0), ParseGuid(r, 1), r.GetString(2), r.GetString(3), r.GetString(4), Text(r, 5), Text(r, 6), Date(r.GetString(7)), Date(r.GetString(8)), r.GetInt64(9)) : null; }
    public async Task UpsertTargetAsync(DeploymentTarget target, long expectedRevision, ProjectEvent projectEvent, CancellationToken cancellationToken = default) => await Transaction(async (c, x) => { await using SqliteCommand q = c.CreateCommand(); q.Transaction = x; q.CommandText = "INSERT INTO deployment_targets(id,project_id,name,mode,destination_path,kelpie_target,config_json,created_at,updated_at,revision) VALUES($id,$project,$name,$mode,$path,$kelpie,$config,$created,$updated,$revision) ON CONFLICT(project_id) DO UPDATE SET name=excluded.name,mode=excluded.mode,destination_path=excluded.destination_path,kelpie_target=excluded.kelpie_target,config_json=excluded.config_json,updated_at=excluded.updated_at,revision=deployment_targets.revision+1 WHERE deployment_targets.revision=$expected;"; AddTarget(q, target); q.Parameters.AddWithValue("$expected", expectedRevision); if (await q.ExecuteNonQueryAsync(cancellationToken) != 1) throw new RevisionConflictException(expectedRevision); await Event(c, x, projectEvent, cancellationToken); }, cancellationToken);
    public async Task AddAsync(Deployment deployment, ProjectEvent projectEvent, CancellationToken cancellationToken = default) => await Write(deployment, null, projectEvent, cancellationToken);
    public async Task UpdateAsync(Deployment deployment, long expectedRevision, ProjectEvent projectEvent, CancellationToken cancellationToken = default) => await Write(deployment, expectedRevision, projectEvent, cancellationToken);
    public async Task<Deployment?> GetAsync(Guid projectId, Guid deploymentId, CancellationToken cancellationToken = default) { await using SqliteConnection c = await Open(cancellationToken); await using SqliteCommand q = c.CreateCommand(); q.CommandText = $"{DeploymentSelect} WHERE project_id=$project AND id=$id;"; q.Parameters.AddWithValue("$project", F(projectId)); q.Parameters.AddWithValue("$id", F(deploymentId)); await using SqliteDataReader r = await q.ExecuteReaderAsync(cancellationToken); return await r.ReadAsync(cancellationToken) ? Read(r) : null; }
    public async Task<IReadOnlyList<Deployment>> ListAsync(Guid projectId, CancellationToken cancellationToken = default) { await using SqliteConnection c = await Open(cancellationToken); await using SqliteCommand q = c.CreateCommand(); q.CommandText = $"{DeploymentSelect} WHERE project_id=$project ORDER BY created_at DESC,id DESC;"; q.Parameters.AddWithValue("$project", F(projectId)); await using SqliteDataReader r = await q.ExecuteReaderAsync(cancellationToken); var list = new List<Deployment>(); while (await r.ReadAsync(cancellationToken)) list.Add(Read(r)); return list; }
    private async Task Write(Deployment d, long? expected, ProjectEvent e, CancellationToken token) => await Transaction(async (c, x) => { await using SqliteCommand q = c.CreateCommand(); q.Transaction = x; q.CommandText = expected is null ? "INSERT INTO deployments(id,project_id,deployment_target_id,build_id,release_id,mode,status,source_commit,destination_path,kelpie_target,previous_deployment_id,rollback_of_deployment_id,started_at,finished_at,actor_type,actor_name,error_code,error_message,created_at,revision) VALUES($id,$project,$target,$build,$release,$mode,$status,$commit,$path,$kelpie,$previous,$rollback,$started,$finished,$actor_type,$actor_name,$error_code,$error_message,$created,$revision);" : "UPDATE deployments SET status=$status,started_at=$started,finished_at=$finished,error_code=$error_code,error_message=$error_message,revision=$revision WHERE id=$id AND project_id=$project AND revision=$expected;"; Add(q, d); if (expected is not null) q.Parameters.AddWithValue("$expected", expected.Value); if (await q.ExecuteNonQueryAsync(token) != 1) throw new RevisionConflictException(expected ?? 0); await Event(c, x, e, token); }, token);
    private async Task Transaction(Func<SqliteConnection, SqliteTransaction, Task> action, CancellationToken token) { await using SqliteConnection c = await Open(token); await using SqliteTransaction x = (SqliteTransaction)await c.BeginTransactionAsync(token); try { await action(c, x); await x.CommitAsync(token); } catch { await x.RollbackAsync(CancellationToken.None); throw; } }
    private async Task<SqliteConnection> Open(CancellationToken token) => await SqliteConnectionFactory.OpenAsync(options, token);
    private static void AddTarget(SqliteCommand q, DeploymentTarget t) { q.Parameters.AddWithValue("$id", F(t.Id)); q.Parameters.AddWithValue("$project", F(t.ProjectId)); q.Parameters.AddWithValue("$name", t.Name); q.Parameters.AddWithValue("$mode", t.Mode); q.Parameters.AddWithValue("$path", t.DestinationPath); q.Parameters.AddWithValue("$kelpie", Db(t.KelpieTarget)); q.Parameters.AddWithValue("$config", Db(t.ConfigJson)); q.Parameters.AddWithValue("$created", F(t.CreatedAt)); q.Parameters.AddWithValue("$updated", F(t.UpdatedAt)); q.Parameters.AddWithValue("$revision", t.Revision); }
    private static void Add(SqliteCommand q, Deployment d) { q.Parameters.AddWithValue("$id", F(d.Id)); q.Parameters.AddWithValue("$project", F(d.ProjectId)); q.Parameters.AddWithValue("$target", F(d.DeploymentTargetId)); q.Parameters.AddWithValue("$build", F(d.BuildId)); q.Parameters.AddWithValue("$release", Db(d.ReleaseId)); q.Parameters.AddWithValue("$mode", d.Mode); q.Parameters.AddWithValue("$status", Status(d.Status)); q.Parameters.AddWithValue("$commit", d.SourceCommit); q.Parameters.AddWithValue("$path", d.DestinationPath); q.Parameters.AddWithValue("$kelpie", Db(d.KelpieTarget)); q.Parameters.AddWithValue("$previous", Db(d.PreviousDeploymentId)); q.Parameters.AddWithValue("$rollback", Db(d.RollbackOfDeploymentId)); q.Parameters.AddWithValue("$started", Db(d.StartedAt)); q.Parameters.AddWithValue("$finished", Db(d.FinishedAt)); q.Parameters.AddWithValue("$actor_type", d.ActorType); q.Parameters.AddWithValue("$actor_name", d.ActorName); q.Parameters.AddWithValue("$error_code", Db(d.ErrorCode)); q.Parameters.AddWithValue("$error_message", Db(d.ErrorMessage)); q.Parameters.AddWithValue("$created", F(d.CreatedAt)); q.Parameters.AddWithValue("$revision", d.Revision); }
    private static async Task Event(SqliteConnection c, SqliteTransaction x, ProjectEvent e, CancellationToken token) { await using SqliteCommand q = c.CreateCommand(); q.Transaction = x; q.CommandText = "INSERT INTO events(id,project_id,entity_type,entity_id,event_type,actor_type,actor_name,before_json,after_json,message,created_at) VALUES($id,$project,$entity_type,$entity,$event_type,$actor_type,$actor_name,$before,$after,$message,$created);"; q.Parameters.AddWithValue("$id", F(e.Id)); q.Parameters.AddWithValue("$project", F(e.ProjectId)); q.Parameters.AddWithValue("$entity_type", e.EntityType); q.Parameters.AddWithValue("$entity", F(e.EntityId)); q.Parameters.AddWithValue("$event_type", e.EventType); q.Parameters.AddWithValue("$actor_type", e.ActorType); q.Parameters.AddWithValue("$actor_name", e.ActorName); q.Parameters.AddWithValue("$before", Db(e.BeforeJson)); q.Parameters.AddWithValue("$after", Db(e.AfterJson)); q.Parameters.AddWithValue("$message", Db(e.Message)); q.Parameters.AddWithValue("$created", F(e.CreatedAt)); await q.ExecuteNonQueryAsync(token); }
    private static Deployment Read(SqliteDataReader r) => Deployment.Restore(ParseGuid(r, 0), ParseGuid(r, 1), ParseGuid(r, 2), ParseGuid(r, 3), GuidAt(r, 4), r.GetString(5), ParseStatus(r.GetString(6)), r.GetString(7), r.GetString(8), Text(r, 9), GuidAt(r, 10), GuidAt(r, 11), DateAt(r, 12), DateAt(r, 13), r.GetString(14), r.GetString(15), Text(r, 16), Text(r, 17), Date(r.GetString(18)), r.GetInt64(19));
    private static string Status(DeploymentStatus value) => value switch { DeploymentStatus.RollingBack => "rolling_back", DeploymentStatus.RolledBack => "rolled_back", DeploymentStatus.RollbackFailed => "rollback_failed", _ => value.ToString().ToLowerInvariant() };
    private static DeploymentStatus ParseStatus(string value) => value switch { "rolling_back" => DeploymentStatus.RollingBack, "rolled_back" => DeploymentStatus.RolledBack, "rollback_failed" => DeploymentStatus.RollbackFailed, _ => Enum.Parse<DeploymentStatus>(value, true) };
    private static Guid ParseGuid(SqliteDataReader r, int i) => Guid.Parse(r.GetString(i), CultureInfo.InvariantCulture); private static Guid? GuidAt(SqliteDataReader r, int i) => r.IsDBNull(i) ? null : ParseGuid(r, i); private static string? Text(SqliteDataReader r, int i) => r.IsDBNull(i) ? null : r.GetString(i); private static DateTimeOffset? DateAt(SqliteDataReader r, int i) => r.IsDBNull(i) ? null : Date(r.GetString(i)); private static object Db(string? v) => v is null ? DBNull.Value : v; private static object Db(Guid? v) => v is null ? DBNull.Value : F(v.Value); private static object Db(DateTimeOffset? v) => v is null ? DBNull.Value : F(v.Value); private static string F(Guid v) => v.ToString("D", CultureInfo.InvariantCulture); private static string F(DateTimeOffset v) => v.ToString("O", CultureInfo.InvariantCulture); private static DateTimeOffset Date(string v) => DateTimeOffset.Parse(v, CultureInfo.InvariantCulture, DateTimeStyles.RoundtripKind);
}
